name: vsngrp-core-be-ws

services:
  redis:
    image: redis:8
    container_name: vsngrp-core-be-ws-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\""]
    volumes:
      - ./redis/data:/data
    ports:
      - "127.0.0.1:6380:6379"
